### ISSUE TITLE
Dolby Vision triggers unnecessarily

### ISSUE THREAD

**Issue by rome1983** [cpm-code/xbmc#16]
When using audio passthru with eARC skipping chapters triggers Dolby Vision.  When directly connected to receiver the issue is not present. 

https://gofile.me/5QThw/3t2ddWe48

**Comment by cpm-code** [comment]
Not sure I can do anything here but probably can give some trouble shoting hints and then can post to CE later see if they have an idea.

**Comment by cpm-code** [comment]
First thing to clarify is how related it is to eARC.

Does it work fine when not using eARC and just using the RV speakers on passthru.

Assuming that is fine the would suggest to extract the edid seen by the Ugoos if both combinations and compare with online edid reader to find any differences.

**Comment by rome1983** [comment]
If I connect directly to receiver the issue is not present. I moved away from connecting directly to receiver since anthem doesn't cache the edid resulting in no Dolby Vision once the receiver is power cycled.  I also tried extracting and loading the edid but that don't seem to work with tv-led dolby vision.

No issue when sending pcm as my LG C1 can't pass DTS. I also tested with True-HD passthru disabled and no issue when sending pcm.

Just tested with just tv speakers and Dolby Vision logo still appears on chapter change.

I have been testing with DV content.

Screen does not go blank and just shows the logo for no apparent reason

**Comment by cpm-code** [comment]
To confirm, issue is seen regardless of eARC and can be reproduced just with direct TV connection?

Any specific DV type like FEL or for all P7 MEL/FEL P8, P5 etc?

-------

@jinior had an issue where the HDRInfo frame got removed I think when skipping (not sure if that is different for chapters or just skipping in general) - anyway looking at that problem gave an insightful element, it was caused because the EL layer processing was being removed and re-added - i.e. needed for FEL; it is like it is starting again and setting up DV after the skip - which may also tie in with you seeing the DV logo)

**Comment by rome1983** [comment]
Yes the issue is seen regardless of eARC and can be reproduced just with direct TV connection. 

Issue is present in all Dolby Vision profiles.

**Comment by rome1983** [comment]
Dolby vision triggers in both cases.

**Comment by cpm-code** [comment]
Checking the code the whole hevc decoder is always reset on skipping / seeking - by design.

It is beyond my skill on the kernel side to know why that then triggers you TV for Dolby Vision but not on mine for example - I tested direct connection from Ugoos to LG E8 no issues for me.

I did come across one parameter you could try - to do with dropping frames and vsync so not really connected but you never know maybe worth a shot:

echo 1 > /sys/module/amvideo/parameters/disable_dv_drop

reboot to reset after any testing with it.

**Comment by rome1983** [comment]
Tried changing the parameter but it didn't help. Thanks
